apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  replicas: 2
  hostname: root
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        argocd-image-updater.argoproj.io/image-list: myapp=docker.io/hndy/microk8s
        argocd-image-updater.argoproj.io/myapp.update-strategy: test-nginx

    spec:
      containers:
        - name: nginx
          image: hndy/microk8s:test-nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: apsdatabase
            - name: DB_PASSWORD
              value: root
